### ISSUE TITLE
Server Issue: Players can not join

### ISSUE THREAD

**Issue by K4N0** [Lightman314/LCTech#6] opened 2022-03-20 18:06 UTC
I have identified this mod as the source of the issue with players not being able to log into the server.
![image](https://user-images.githubusercontent.com/10932905/159175916-bdedb131-891e-4dce-871a-41a4773b3b59.png)
This only happens with a loaded world. I believe a user placed a block or something.
When I disable the mod, run the server and then re-add it. It's fine since I believe the block was removed upon joining the world.
However when I re-add a backed up world. The error begins to happen again.

I am not entirely sure of how or where the issue is, but the only way to fix my server was to remove this mod.
I have verified uniquely that this mod is the cause. When attempting to log in, the server doesn't produce very much info.

[lctech mod issue latest log.txt](https://github.com/Lightman314/LCTech/files/8311875/lctech.mod.issue.latest.log.txt)

Second issue is 
Also when players place the energy transfer server, the shops all get messed up and only the last one shows up using the terminal.

Lastly, This is on my modpack Cataclysm Zombie Apocalypse.
https://www.curseforge.com/minecraft/modpacks/cataclysm-zombie-apocalypse

**Comment by Lightman314** [comment] 2022-03-20 18:22
I cannot make heads or tails out of the log that you sent me, although I do have a theory as to why removing LC Tech fixed it. It's not because anything was wrong with LC Tech, it's just that removing LC Tech shrunk the number of universal traders down to a smaller size, such that the packet sent on login was now small enough to not exceed the limit (and as such this is a Lightman's Currency issue technically, since it's in charge of sending the packet). I encountered a similar issue with players being unable to open Item Trader Servers that had trade log files that were too large (as the max packet size for opening menus is far smaller than the normal packet size limit), and now I suppose that I'm probably encountering a similar error now with the packet size for the universal trader initialization packet that is sent to players on login... I'll probably have to split it up and send multiple packets (one for each trader to be 100% safe) when the player logs in to the server.

Edit: I'll see if I can get a hotfix for Lightman's Currency that fixes this issue, although I make no promises, as this is likely going to be a difficult issue to reproduce.

**Comment by K4N0** [comment] 2022-03-20 18:42
Apologies, Yes after narrowing it down a bit more. It is a lightmans currency mod issue.
After removing your mod and just having lightmans with the backed up world. It still would not allow me to login.

**Comment by Lightman314** [comment] 2022-03-20 18:44
Alrighty, I'll see if I can get that hotfix working, although on my end I can really only just check to make sure the new method doesn't break the universal traders entirely and hope it fixes your issue. Just out of curiosity, about how many trading servers would you estimate exists on your servers world? ~100? more? less?

**Comment by K4N0** [comment] 2022-03-20 18:47
> Alrighty, I'll see if I can get that hotfix working, although on my end I can really only just check to make sure the new method doesn't break the universal traders entirely and hop it fixes your issue. Just out of curiosity, about how many trading servers would you estimate exists on your servers world? ~100? more? less?

It is a fairly new modpack with very few servers. I would estimate about 10. About 4 are admin servers, I have 2 and a few players with maybe 6ish more. I have no problem wiping the world, but I assume it will happen again. Setting up all the shops again with pricing is very time consuming.

**Comment by Lightman314** [comment] 2022-03-20 18:51
Only 10? I'm legit amazed that it caused an issue with only that many, cause I've been on servers that have had at least 4-5 times that many with no problems... Have there been a lot of interactions with those traders, cause if so the bloated size might have been  caused by a large number of text logs from trade interactions. If that's the case I'll likely need to re-implement the log size limit in addition to separating the trader synchronization limits.

**Comment by K4N0** [comment] 2022-03-20 18:56
The admin shop also has very simple trades as well as my 2 servers. While playing, I did notice a player saying he was going to be adding enchanted armor to the shops. Is it possible that adding too many nbt tags or enchantments as such may increase something where it would cause such an issue. While researching, I encountered a similar issue with refined storage where if a user added in too many items with nbt tags, it would cause the user to be unable to view the items in the storage unit as well as in other issues login with a similar error.

**Comment by K4N0** [comment] 2022-03-20 18:58
I'll continue to do more testing by adding in items after I wipe the lc servers off the mc server and see if I can replicate the issue.

**Comment by Lightman314** [comment] 2022-03-20 19:13
By interactions, I mostly meant large amounts of players actually interacting with the trades, adding text to the text logger, as the text logger can't exactly store the text in a small amount of space (each text line probably contains as much NBT text as an enchanted tool, so if someone buys 100 stacks of cobble stone that's the same as adding 100 fully enchanted and named tools to the item storage), although adding enchanted items to the shop would probably bloat that size by a little bit causing the issue to appear sooner.
I'll probably re-implement the logSize server config option to limit the maximum number of text log entries to help limit packet sizes just to be safe, cause lets be honest, who cares who purchased something 100 trades ago... I'll also make sure that it applies the limit when the logger is loaded from nbt so that it can be applied retroactively to fix traders that are already too big for the packet.

**Comment by K4N0** [comment] 2022-03-20 19:18
I think you are correct. This seems to have happened after I added wood to the admin shop and even I purchased Stacks upon Stacks, even 3 inventory's full of wood at a time. I actually created an issue to allow more than 3 stacks to be purchased at a time and for the items to go directly into my inventory. I would love to disable the logs for sure or only show the most recent.

**Comment by K4N0** [comment] 2022-03-20 19:23
> By interactions, I mostly meant large amounts of players actually interacting with the trades, adding text to the text logger, as the text logger can't exactly store the text in a small amount of space (each text line probably contains as much NBT text as an enchanted tool, so if someone buys 100 stacks of cobble stone that's the same as adding 100 fully enchanted and named tools to the item storage), although adding enchanted items to the shop would probably bloat that size by a little bit causing the issue to appear sooner. I'll probably re-implement the logSize server config option to limit the maximum number of text log entries to help limit packet sizes just to be safe, cause lets be honest, who cares who purchased something 100 trades ago... I'll also make sure that it applies the limit when the logger is loaded from nbt so that it can be applied retroactively to fix traders that are already too big for the packet.

Where would the log files be found. Maybe I can delete them and help identify if that is where the issue is at. I'm testing out the theory and deleting the lightmanscurrency_trading_office.dat in the world folder. In the world > data folder.

**Comment by K4N0** [comment] 2022-03-20 19:29
Confirmed, after adding a single file to the server lightmanscurrency_trading_office.dat from the backup world.
I am unable to login.
[lightmanscurrency_trading_office.zip](https://github.com/Lightman314/LCTech/files/8312016/lightmanscurrency_trading_office.zip)

**Comment by K4N0** [comment] 2022-03-20 19:37
Also the modpack is a zombie apocalypse type. Which I made it easy for players to purchase bullets from the shop as well. I'm guessing this would increase the heck out of the logs.

**Comment by Lightman314** [comment] 2022-03-20 19:43
Well with the logLimit config option you'll be able to limit the log size to as low as you want (even 0 if you want to disable them entirely). As for where they are saved, they're included in each Universal Trader's data ("ItemShopHistory" tag) in the lightmanscurrency_trading_office.dat file (as you accurately guessed). That said if you wait for the update, you won't need to manually remove the text logs, as the logLimit config option will shrink them appropriately.

**Comment by Lightman314** [comment] 2022-03-20 21:26
Should be fixed in Lightman's Currency v1.0.5.3. Closing the issue.

**Closed as completed by Lightman314** 2022-03-20 21:26 UTC
Labels: bug
