### ISSUE TITLE
Energy Trader Interface does not work

### ISSUE THREAD

**Issue by killeroid356** [Lightman314/LCTech#8] opened 2022-11-06 21:55 UTC
too lazy to write this again so have some screenshots

![image](https://user-images.githubusercontent.com/34097198/200197243-7d41fdb8-fd50-4f23-875a-4fe1b9aadd06.png)
![image](https://user-images.githubusercontent.com/34097198/200197255-db63ad56-1227-4371-81b2-170438d4c065.png)

**Comment by Lightman314** [comment] 2022-11-06 23:31
It would appear that neither Fluid nor Energy traders were set to implement an interface required for the Trader Interfaces to function as intended. A fix should be out shortly.

**Comment by Lightman314** [comment] 2022-11-07 03:42
Fixed in v0.1.0.2

**Closed as completed by Lightman314** 2022-11-07 03:42 UTC
